/**
 * AUTOGENERATED
 */
import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity('jwks')
export class Jwks {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'publicKey' })
  publicKey: string;

  @Column('text', { name: 'privateKey' })
  privateKey: string;

  @Column({ type: 'timestamp', name: 'createdAt' })
  createdAt: Date;

  @Column({ type: 'timestamp', name: 'expiresAt', nullable: true })
  expiresAt: Date | null;
}
