/**
 * AUTOGENERATED
 */
import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { User } from './User';

@Entity('oauthApplication')
export class OauthApplication {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'name', nullable: true })
  name: string | null;

  @Column('text', { name: 'icon', nullable: true })
  icon: string | null;

  @Column('text', { name: 'metadata', nullable: true })
  metadata: string | null;

  @Column('text', { name: 'clientId', nullable: true, unique: true })
  clientId: string | null;

  @Column('text', { name: 'clientSecret', nullable: true })
  clientSecret: string | null;

  @Column('text', { name: 'redirectUrls', nullable: true })
  redirectUrls: string | null;

  @Column('text', { name: 'type', nullable: true })
  type: string | null;

  @Column('boolean', { name: 'disabled', nullable: true, default: false })
  disabled: boolean | null;

  @Index('oauthApplication_userId_idx')
  @Column('text', { name: 'userId', nullable: true })
  userId: string | null;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: true })
  @JoinColumn({ name: 'userId', referencedColumnName: 'id' })
  user?: User;

  @Column({ type: 'timestamp', name: 'createdAt', nullable: true })
  createdAt: Date | null;

  @Column({ type: 'timestamp', name: 'updatedAt', nullable: true })
  updatedAt: Date | null;
}
