/**
 * AUTOGENERATED
 */
import { Column, Entity, JoinColumn, ManyToOne, PrimaryColumn } from 'typeorm';
import { OauthClient } from './OauthClient';
import { User } from './User';

@Entity('oauthConsent')
export class OauthConsent {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'clientId' })
  clientId: string;

  @ManyToOne(() => OauthClient, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'clientId', referencedColumnName: 'clientId' })
  client: OauthClient;

  @Column('text', { name: 'userId', nullable: true })
  userId: string | null;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: true })
  @JoinColumn({ name: 'userId', referencedColumnName: 'id' })
  user?: User;

  @Column('text', { name: 'referenceId', nullable: true })
  referenceId: string | null;

  @Column('text', { name: 'scopes' })
  scopes: string;

  @Column({ type: 'timestamp', name: 'createdAt', nullable: true })
  createdAt: Date | null;

  @Column({ type: 'timestamp', name: 'updatedAt', nullable: true })
  updatedAt: Date | null;
}
