/**
 * AUTOGENERATED
 */
import { Column, Entity, JoinColumn, ManyToOne, PrimaryColumn } from 'typeorm';
import { OauthClient } from './OauthClient';
import { Session } from './Session';
import { User } from './User';

@Entity('oauthRefreshToken')
export class OauthRefreshToken {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'token', unique: true })
  token: string;

  @Column('text', { name: 'clientId' })
  clientId: string;

  @ManyToOne(() => OauthClient, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'clientId', referencedColumnName: 'clientId' })
  client: OauthClient;

  @Column('text', { name: 'sessionId', nullable: true })
  sessionId: string | null;

  @ManyToOne(() => Session, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'sessionId', referencedColumnName: 'id' })
  session?: Session;

  @Column('text', { name: 'userId' })
  userId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'userId', referencedColumnName: 'id' })
  user: User;

  @Column('text', { name: 'referenceId', nullable: true })
  referenceId: string | null;

  @Column({ type: 'timestamp', name: 'expiresAt', nullable: true })
  expiresAt: Date | null;

  @Column({ type: 'timestamp', name: 'createdAt', nullable: true })
  createdAt: Date | null;

  @Column({ type: 'timestamp', name: 'revoked', nullable: true })
  revoked: Date | null;

  @Column({ type: 'timestamp', name: 'authTime', nullable: true })
  authTime: Date | null;

  @Column('text', { name: 'scopes' })
  scopes: string;
}
