/**
 * AUTOGENERATED
 */
import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { User } from './User';

@Entity('passkey')
export class Passkey {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'name', nullable: true })
  name: string | null;

  @Column('text', { name: 'publicKey' })
  publicKey: string;

  @Index('passkey_userId_idx')
  @Column('text', { name: 'userId' })
  userId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'userId', referencedColumnName: 'id' })
  user: User;

  @Index('passkey_credentialID_idx')
  @Column('text', { name: 'credentialID' })
  credentialID: string;

  @Column('integer', { name: 'counter' })
  counter: number;

  @Column('text', { name: 'deviceType' })
  deviceType: string;

  @Column('boolean', { name: 'backedUp' })
  backedUp: boolean;

  @Column('text', { name: 'transports', nullable: true })
  transports: string | null;

  @Column({ type: 'timestamp', name: 'createdAt', nullable: true })
  createdAt: Date | null;

  @Column('text', { name: 'aaguid', nullable: true })
  aaguid: string | null;
}
