/**
 * AUTOGENERATED
 */
import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity('user')
export class User {
  @PrimaryColumn('text')
  id: string;

  @Column('text', { name: 'name' })
  name: string;

  @Column('text', { name: 'email', unique: true })
  email: string;

  @Column('boolean', { name: 'emailVerified', default: false })
  emailVerified: boolean;

  @Column('text', { name: 'image', nullable: true })
  image: string | null;

  @Column({ type: 'timestamp', name: 'createdAt' })
  createdAt: Date;

  @Column({ type: 'timestamp', name: 'updatedAt' })
  updatedAt: Date;
}
