/**
 * AUTOGENERATED
 */
import { Column, Entity, Index, PrimaryColumn } from 'typeorm';

@Entity('verification')
export class Verification {
  @PrimaryColumn('text')
  id: string;

  @Index('verification_identifier_idx')
  @Column('text', { name: 'identifier' })
  identifier: string;

  @Column('text', { name: 'value' })
  value: string;

  @Column({ type: 'timestamp', name: 'expiresAt' })
  expiresAt: Date;

  @Column({ type: 'timestamp', name: 'createdAt' })
  createdAt: Date;

  @Column({ type: 'timestamp', name: 'updatedAt' })
  updatedAt: Date;
}
